version: '3.8'

services:
  backend:
    build: ./back-end
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app

  frontend:
    build: ./front-end
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
