version: '3.8'
networks:
  sn:
    driver: bridge

services:
  backend:
    build: ./back-end
    ports:
      - "8080:8080"
    networks:
      - sn

  frontend:
    build: ./front-end
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - sn
