CREATE TABLE IF NOT EXISTS followers (
    followerId INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    followedId INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (followerId, followedId)
);
