CREATE TABLE IF NOT EXISTS PostReactions (
    id INTEGER , --PRIMARY KEY AUTOINCREMENT,
    postId INTEGER NOT NULL, --REFERENCES Posts(id) ON DELETE CASCADE,
    userId INTEGER NOT NULL ,--REFERENCES Users(id) ON DELETE CASCADE,
    reactionType INTEGER NOT NULL CHECK (reactionType IN (-1, 0, 1)),
    UNIQUE(postId, userId)
);
